# Site settings
title: New Naratif Operations Manual
description: Internal documentation for WordPress operations and procedures
baseurl: "/new-naratif-docs"
url: "https://notalentgeek.github.io"

# Theme
theme: just-the-docs

# Just the Docs Collections Configuration
just_the_docs:
  collections:
    emergency:
      name: Emergency Procedures
      nav_exclude: false
      search_exclude: false
    daily:
      name: Daily Operations
      nav_exclude: false
      search_exclude: false
    maintenance:
      name: Maintenance Tasks
      nav_exclude: false
      search_exclude: false

collections:
  emergency:
    output: true
    permalink: "/:path/"
  daily:
    output: true
    permalink: "/:path/"
  maintenance:
    output: true
    permalink: "/:path/"

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links
aux_links:
  "View on GitHub":
    - "//github.com/notalentgeek/new-naratif-docs"
  "Main Website":
    - "https://newnaratif.com"
aux_links_new_tab: true

# Footer
footer_content: "Copyright &copy; 2025 New Naratif. Internal documentation - do not share."

# Color scheme
color_scheme: light
